# Generated by Django 2.1.2 on 2018-11-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=250)),
                ('source', models.CharField(max_length=200)),
                ('date_published', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('dom_tone', models.CharField(max_length=300)),
                ('image', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
