# Generated by Django 2.1.2 on 2018-12-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('url', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('source', models.CharField(max_length=200)),
                ('date_published', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('dom_tone', models.CharField(max_length=300)),
            ],
        ),
    ]
