# Generated by Django 2.1.5 on 2019-01-24 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='Untitled', max_length=180)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('url', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('source', models.CharField(max_length=200)),
                ('date_published', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('dom_tone', models.CharField(max_length=300)),
            ],
        ),
    ]
