# Generated by Django 2.1.2 on 2018-12-19 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='date_created',
        ),
    ]
