# Generated by Django 2.1.5 on 2019-01-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_auto_20190125_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.CharField(default='Untitled', max_length=180),
        ),
    ]
